### ISSUE TITLE
[FR] Intake

### ISSUE THREAD

**Issue by LordBBQ** [team5985/InfiniteRecharge#3]
**Is your feature request related to a problem? Please describe.**
No

The driver can push a button and control the intake.

**Describe alternatives you've considered**
Vacuum cleaner

**Comment by nomisimon** [comment]
Has thought been given to how the intake will actually be controlled?  

Will there be a different button to extend/retract the intake and another one to actually spin the roller?  Or will the driver press a button to deploy the intake and when it is deployed the roller will start automatically.

Will the intake retract automatically or rely on the driver(s) to retract it?
