### ISSUE TITLE
control panel

### ISSUE THREAD

**Issue by hugosnoek** [team5985/InfiniteRecharge#8]
Is your feature request related to a problem? Please describe.
no

Describe the solution you'd like
an arm comes out and will go on to the wheel the colour sensor will be above the colour with a shield around it to stop the light from coming in with a wheel next to it to spin it to the right colour  

Describe alternatives you've considered
we could use the force
we could have the arm already out
we could just not do the control panel

Could this cause any issues?
when coming out it could go to far and break
the wheel could be going to fast and not be able to read the colours
the colour sensor could be broken and not see the colour and keep on spinning forever

**Comment by LordBBQ** [comment]
@hugosnoek @SashimiDude You could work together on this on the weekend.

**Comment by SashimiDude** [comment]
@LordBBQ 
I`m pretty sure it can go into dodgy as if not DTT since its already in tele-op controller
